{% set name = "adios_db" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/adios_oil_database/archive/v{{ version }}.tar.gz
  sha256: 4f8188c762792386275f4d89129676f2b9985172213b299aa1ac88013a00a855

build:
  number: 0
  noarch: python

outputs:
  - name: adios_db
    script: build_base.sh
    entry_points:
      - adios_db_add_labels = adios_db.scripts.add_labels:add_the_labels
      - adios_db_assign_ids = adios_db.scripts.assign_ids:main
      - adios_db_backup = adios_db.scripts.db_backup:backup_db_cmd
      - adios_db_import = adios_db.scripts.db_import:import_db_cmd
      - adios_db_init = adios_db.scripts.db_initialize:init_db_cmd
      - adios_db_oil_query = adios_db.scripts.oil_query:oil_query_cmd
      - adios_db_process_json = adios_db.scripts.process_json:run_through
      - adios_db_read_noaa_csv = adios_db.scripts.read_noaa_csv:main
      - adios_db_restore = adios_db.scripts.db_restore:restore_db_cmd
      - adios_db_update_test_data = adios_db.scripts.update_test_data:main
      - adios_db_validate = adios_db.scripts.validate:main
      - adios_db_eccc_compare = adios_db.scripts.eccc_compare_oils:compare_eccc_oils_cmd
    requirements:
      host:
        - python >=3.9
        - pip
        - setuptools
      run:
        - python >=3.9
        - numpy >=1.24
        - pynucos >=3.3
    test:
      imports:
        - adios_db
      commands:
        - adios_db_process_json
        - adios_db_validate

  - name: adios-db
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('adios_db', max_pin="x.x.x") }}
    test:
      imports:
        - adios_db

about:
  home: https://github.com/NOAA-ORR-ERD/adios_oil_database
  summary: Package for working with data in the NOAA ADIOS Oil Database
  description: |
    Python package for managing oil properties data for the ADIOS Oil Databse.
    It provides code for:
    * Importing data
    * Reading and writing the JSON format
    * A data validation framework (there is a small amount of validation included, it is fairly starightformward to add more.
    * Some computation on the data (interpolation, etc.)
    * Code to build an oil definition as required by the NOAA GNOME oil weathering model.
  license: CC0-1.0
  license_file: LICENSE.txt
  doc_url: https://noaa-orr-erd.github.io/adios_oil_database/
  dev_url: https://github.com/NOAA-ORR-ERD/adios_oil_database

extra:
  recipe-maintainers:
    - JamesMakela-NOAA
    - ChrisBarker-NOAA
